config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  get "/confirmation_sent", to: "static_pages#confirmation_sent", as: :confirmation_sent
  get "/today", to: "lists#today", as: :today
  get "/upcoming", to: "lists#upcoming", as: :upcoming
  get "/archived", to: "lists#archived", as: :archived
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get "/signup", to: "users/registrations#new"
    get "/login", to: "users/sessions#new"
    delete "/logout", to: "users/sessions#destroy"
    get "/account/edit", to: "users/registrations#edit"
  end

  resources :todos, only: [ :new, :create, :edit, :update, :destroy ]  do
    member { post :copy }
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  def today
    @todos = current_user.todos.today
    render_after_cancel_button("today")
  end

  def upcoming
    @todos = current_user.todos.upcoming.order(due_at: :desc)
    render_after_cancel_button("upcoming")
  end

  def archived
    @todos = current_user.todos.archived.order(due_at: :desc)
    render_after_cancel_button("archived")
  end

  private
    # 新規作成・編集 キャンセルボタンの後の処理
    def render_after_cancel_button(source)
      respond_to do |format|
        format.html   # HTMLで通常のページ遷移するとき
        format.turbo_stream do
          if params[:mode] == "edit" && params[:todo_id].present?
            @todo = current_user.todos.find(params[:todo_id])
            render turbo_stream:
            turbo_stream.replace(
              "todo_#{@todo.id}",
              partial: "todos/todo",
              locals: { todo: @todo, source: source }
            )
          else
            render turbo_stream:
            turbo_stream.replace(
              "todo_#{source}_form",
              partial:  "lists/add_todo_button",
              locals:   { source: source }
            )
          end
        end
      end
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_add_todo_button.html.erb
<div id ="add_todo_button_<%= source %>">
  <div class="mt-6">
    <%= link_to new_todo_path(source: source ), 
                data: { turbo_stream: true },
                class: "inline-flex items-center text-gray-400 hover:text-gray-700 transition-colors" do %>
      <svg xmlns="http://www.w3.org/2000/svg"
          class="w-5 h-5 mr-1 text-gray-400 hover:text-gray-700 transition-colors"
          fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M12 4v16m8-8H4" />
      </svg>
      todoを追加
    <% end %>
  </div>
</div>

app/views/lists/_todos_list.html.erb
<% todos.group_by { |todo| todo.due_at.to_date }.each do |date, todos_for_date| %> <%# todos_for_date は同じ日(6/1等)の塊のtodo%>
  <div class="mb-6" id ="todos_group_<%= date %>">
    <!-- 日付見出し -->
    <h2 class="text-xl font-semibold text-gray-700 mb-2"  >
      <%= I18n.l(date, format: :todo) %>
    </h2>
    <!-- タスク一覧 -->
    <ul id = "todos_<%= source %>" class="space-y-4 list-none">
      <%= render partial: "todos/todo", collection: todos_for_date, as: :todo , locals: { source: source }%>
    </ul>
  </div>
<% end %>

app/views/lists/archived.html.erb
<div class="relative max-w-2xl mx-auto px-4 py-6">
  <!-- 見出し -->
  <h1 class="text-2xl font-bold mb-2">アーカイブ</h1>

  <!-- タスク一覧 -->
  <div id= "todos_list_wrapper">
    <%= render "todos_list",todos: @todos, source: "archived" %>
  </div>

</div>

app/views/lists/today.html.erb
<div class="relative max-w-2xl mx-auto px-4 py-6">
  <!-- 見出し -->
  <h1 class="text-2xl font-bold mb-2">今日</h1>

  <!-- 日付ごとのグループ化 -->
  <div id= "todos_list_wrapper">
    <%= render "todos_list", todos: @todos, source: "today" %>
  </div>

  <!-- タスク追加リンク -->
  <div>
    <%= render "add_todo_button", source: "today" %>
  </div>
  

</div>

app/views/lists/upcoming.html.erb
<div class="relative max-w-2xl mx-auto px-4 py-6">
  <!-- 見出し -->
  <h1 class="text-2xl font-bold mb-2">近日予定</h1>

  <!-- タスク一覧 -->
  <div id= "todos_list_wrapper">
    <%= render "todos_list", todos: @todos, source: "upcoming" %>
  </div>

  <!-- タスク追加リンク -->
  <div>
    <%= render "lists/add_todo_button", source: "upcoming" %>
  </div>
</div>